#!/usr/bin/env python3
"""
Gallery Generator — auto-discovers image files in content directories
(those containing a README.md) and writes shared/gallery.js.

Topic labels and links are derived from the directory structure and
label_overrides in shared/toc-overrides.json.

Usage:
    python3 Dev-Tools/generate-gallery.py             # regenerate gallery.js
    python3 Dev-Tools/generate-gallery.py --dry-run   # preview without writing
    python3 Dev-Tools/generate-gallery.py --check     # exit 1 if gallery.js is stale
"""

import os
import sys
import json
import argparse
from pathlib import Path

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}

SKIP_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", "env",
    ".env", "dist", "build", ".next", ".nuxt", "target", ".cache",
    ".idea", ".vscode", "__MACOSX", ".DS_Store",
}

ROOT_SKIP = {"shared"}


def auto_label(name: str) -> str:
    """Convert a directory name to a human-readable label."""
    return name.replace("-", " ").replace("_", " ")


def find_topic_dir(rel_dir: str, readme_dirs: set) -> str | None:
    """Walk up from rel_dir to find the nearest directory with a README.md."""
    parts = rel_dir.split("/")
    for i in range(len(parts), 0, -1):
        candidate = "/".join(parts[:i])
        if candidate in readme_dirs:
            return candidate
    return None


def make_alt(filename: str) -> str:
    """Derive alt text from a filename."""
    stem = Path(filename).stem
    return stem.replace("_", " ").replace("-", " ")


def discover_gallery(root: Path, exclude_paths: set) -> tuple[set, list]:
    """
    Walk the repo and return:
    - readme_dirs: set of relative dir paths that contain a README.md
    - images: list of (rel_file_path, rel_dir_path) for discovered images
    """
    readme_dirs = set()
    images = []

    for dirpath, dirs, files in os.walk(root):
        current = Path(dirpath)
        dirs[:] = sorted([d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")])

        try:
            rel = current.relative_to(root)
        except ValueError:
            continue

        parts = rel.parts
        if not parts:
            continue

        section = parts[0]
        if section in ROOT_SKIP:
            dirs.clear()
            continue

        rel_str = "/".join(parts)

        if rel_str in exclude_paths or any(
            rel_str.startswith(s + "/") for s in exclude_paths
        ):
            dirs.clear()
            continue

        if any(f.lower() == "readme.md" for f in files):
            readme_dirs.add(rel_str)

        for f in sorted(files):
            if Path(f).suffix.lower() in IMAGE_EXTENSIONS:
                images.append((rel_str + "/" + f, rel_str))

    return readme_dirs, images


def build_gallery(root: Path, overrides: dict) -> list:
    """Build the GALLERY array from auto-discovered images."""
    label_overrides = overrides.get("label_overrides", {})
    gallery_cfg = overrides.get("gallery", {})
    exclude_paths = set(gallery_cfg.get("exclude_paths", []))
    alt_overrides = gallery_cfg.get("alt_overrides", {})

    readme_dirs, images = discover_gallery(root, exclude_paths)

    gallery = []
    for rel_file, rel_dir in images:
        topic_dir = find_topic_dir(rel_dir, readme_dirs)
        if topic_dir is None:
            continue

        label = label_overrides.get(topic_dir) or auto_label(Path(topic_dir).name)
        href = f"/shared/md.html?src={topic_dir}/README.md"
        filename = rel_file.split("/")[-1]
        alt = alt_overrides.get(rel_file) or make_alt(filename)

        gallery.append({
            "src": "/" + rel_file,
            "topic": label,
            "topicHref": href,
            "alt": alt,
        })

    return gallery


def render_gallery_js(gallery: list) -> str:
    """Produce the contents of gallery.js."""
    header = (
        "// AUTO-GENERATED by Dev-Tools/generate-gallery.py — do not edit by hand.\n"
        "// To customise entries, edit shared/toc-overrides.json and re-run.\n"
        "var GALLERY = "
    )
    data = json.dumps(gallery, indent=2, ensure_ascii=False)
    return header + data + ";\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate shared/gallery.js from image discovery + overrides."
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Print generated JS without writing")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if gallery.js would change (useful in CI)")
    args = parser.parse_args()

    root = Path(__file__).parent.parent.resolve()
    overrides_path = root / "shared" / "toc-overrides.json"
    gallery_path = root / "shared" / "gallery.js"

    overrides = {}
    if overrides_path.exists():
        overrides = json.loads(overrides_path.read_text(encoding="utf-8"))

    gallery = build_gallery(root, overrides)
    output = render_gallery_js(gallery)

    if args.dry_run:
        print(output)
        return

    if args.check:
        current = gallery_path.read_text(encoding="utf-8") if gallery_path.exists() else ""
        if current != output:
            print("gallery.js is stale — run generate-gallery.py to update.")
            sys.exit(1)
        print("gallery.js is up to date.")
        return

    gallery_path.write_text(output, encoding="utf-8")
    topics = set(item["topic"] for item in gallery)
    print(f"OK  Wrote {len(gallery)} images across {len(topics)} topics -> shared/gallery.js")
    for topic in sorted(topics):
        count = sum(1 for item in gallery if item["topic"] == topic)
        print(f"   {topic}: {count} images")


if __name__ == "__main__":
    main()
