// AUTO-GENERATED by Dev-Tools/generate-gallery.py — do not edit by hand.
// To customise entries, edit shared/toc-overrides.json and re-run.
var GALLERY = [
  {
    "src": "/Mathematics/Numerical-Methods/Chaos-Dynamics/chaos_bifurcation_artistic.png",
    "topic": "Chaos & Dynamics",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Chaos-Dynamics/README.md",
    "alt": "chaos bifurcation artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Chaos-Dynamics/chaos_diagnostic.png",
    "topic": "Chaos & Dynamics",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Chaos-Dynamics/README.md",
    "alt": "chaos diagnostic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Chaos-Dynamics/chaos_double_pendulum_artistic.png",
    "topic": "Chaos & Dynamics",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Chaos-Dynamics/README.md",
    "alt": "chaos double pendulum artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Chaos-Dynamics/chaos_lorenz_artistic.png",
    "topic": "Chaos & Dynamics",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Chaos-Dynamics/README.md",
    "alt": "chaos lorenz artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/FFT-Spectral/fft_2d_spectrum.png",
    "topic": "FFT & Spectral",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/FFT-Spectral/README.md",
    "alt": "fft 2d spectrum"
  },
  {
    "src": "/Mathematics/Numerical-Methods/FFT-Spectral/fft_chebyshev.png",
    "topic": "FFT & Spectral",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/FFT-Spectral/README.md",
    "alt": "fft chebyshev"
  },
  {
    "src": "/Mathematics/Numerical-Methods/FFT-Spectral/fft_power_spectrum.png",
    "topic": "FFT & Spectral",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/FFT-Spectral/README.md",
    "alt": "fft power spectrum"
  },
  {
    "src": "/Mathematics/Numerical-Methods/FFT-Spectral/fft_spectral_artistic.gif",
    "topic": "FFT & Spectral",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/FFT-Spectral/README.md",
    "alt": "fft spectral artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/FFT-Spectral/fft_spectral_artistic.png",
    "topic": "FFT & Spectral",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/FFT-Spectral/README.md",
    "alt": "fft spectral artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/FFT-Spectral/fft_spectral_diff.png",
    "topic": "FFT & Spectral",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/FFT-Spectral/README.md",
    "alt": "fft spectral diff"
  },
  {
    "src": "/Mathematics/Numerical-Methods/FFT-Spectral/fft_timing.png",
    "topic": "FFT & Spectral",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/FFT-Spectral/README.md",
    "alt": "fft timing"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Interpolation/interpolation_artistic.png",
    "topic": "Interpolation",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Interpolation/README.md",
    "alt": "interpolation artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Interpolation/interpolation_diagnostic.png",
    "topic": "Interpolation",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Interpolation/README.md",
    "alt": "interpolation diagnostic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Interpolation/runges_phenomenon.png",
    "topic": "Interpolation",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Interpolation/README.md",
    "alt": "Runge's phenomenon"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Numerical-Integration/quadrature_convergence.png",
    "topic": "Numerical Integration",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Numerical-Integration/README.md",
    "alt": "quadrature convergence"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Numerical-Integration/quadrature_diffraction.gif",
    "topic": "Numerical Integration",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Numerical-Integration/README.md",
    "alt": "quadrature diffraction"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Numerical-Integration/quadrature_diffraction.png",
    "topic": "Numerical Integration",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Numerical-Integration/README.md",
    "alt": "quadrature diffraction"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Numerical-Integration/quadrature_panels.png",
    "topic": "Numerical Integration",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Numerical-Integration/README.md",
    "alt": "quadrature panels"
  },
  {
    "src": "/Mathematics/Numerical-Methods/ODE-Solvers/ode_adams_comparison.png",
    "topic": "ODE Solvers",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/ODE-Solvers/README.md",
    "alt": "ode adams comparison"
  },
  {
    "src": "/Mathematics/Numerical-Methods/ODE-Solvers/ode_phase_space.png",
    "topic": "ODE Solvers",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/ODE-Solvers/README.md",
    "alt": "ode phase space"
  },
  {
    "src": "/Mathematics/Numerical-Methods/ODE-Solvers/ode_solvers_diagnostic.png",
    "topic": "ODE Solvers",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/ODE-Solvers/README.md",
    "alt": "ode solvers diagnostic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Reaction-Diffusion/rd_diagnostic.png",
    "topic": "Reaction-Diffusion",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Reaction-Diffusion/README.md",
    "alt": "rd diagnostic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Reaction-Diffusion/rd_reaction_fronts_artistic.png",
    "topic": "Reaction-Diffusion",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Reaction-Diffusion/README.md",
    "alt": "rd reaction fronts artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Reaction-Diffusion/rd_turing_mosaic_artistic.png",
    "topic": "Reaction-Diffusion",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Reaction-Diffusion/README.md",
    "alt": "rd turing mosaic artistic"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Root-Finding/newton_fractal.png",
    "topic": "Root Finding",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Root-Finding/README.md",
    "alt": "newton fractal"
  },
  {
    "src": "/Mathematics/Numerical-Methods/Root-Finding/root_finding_diagnostic.png",
    "topic": "Root Finding",
    "topicHref": "/shared/md.html?src=Mathematics/Numerical-Methods/Root-Finding/README.md",
    "alt": "root finding diagnostic"
  },
  {
    "src": "/Physics/Jupiter-Satellite-Orbits/jupiter_artistic.png",
    "topic": "Jupiter Satellite Orbits",
    "topicHref": "/shared/md.html?src=Physics/Jupiter-Satellite-Orbits/README.md",
    "alt": "jupiter artistic"
  },
  {
    "src": "/Physics/Jupiter-Satellite-Orbits/jupiter_diagnostic.png",
    "topic": "Jupiter Satellite Orbits",
    "topicHref": "/shared/md.html?src=Physics/Jupiter-Satellite-Orbits/README.md",
    "alt": "jupiter diagnostic"
  },
  {
    "src": "/Physics/Jupiter-Satellite-Orbits/jupiter_orbits.gif",
    "topic": "Jupiter Satellite Orbits",
    "topicHref": "/shared/md.html?src=Physics/Jupiter-Satellite-Orbits/README.md",
    "alt": "jupiter orbits"
  },
  {
    "src": "/Physics/Percolation/perc_bootstrap.gif",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc bootstrap"
  },
  {
    "src": "/Physics/Percolation/perc_bootstrap_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc bootstrap artistic"
  },
  {
    "src": "/Physics/Percolation/perc_diagnostic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc diagnostic"
  },
  {
    "src": "/Physics/Percolation/perc_directed.gif",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc directed"
  },
  {
    "src": "/Physics/Percolation/perc_directed_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc directed artistic"
  },
  {
    "src": "/Physics/Percolation/perc_explosive.gif",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc explosive"
  },
  {
    "src": "/Physics/Percolation/perc_explosive_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc explosive artistic"
  },
  {
    "src": "/Physics/Percolation/perc_gradient.gif",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc gradient"
  },
  {
    "src": "/Physics/Percolation/perc_gradient_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc gradient artistic"
  },
  {
    "src": "/Physics/Percolation/perc_invasion.gif",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc invasion"
  },
  {
    "src": "/Physics/Percolation/perc_invasion_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc invasion artistic"
  },
  {
    "src": "/Physics/Percolation/perc_lattice_above_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc lattice above artistic"
  },
  {
    "src": "/Physics/Percolation/perc_lattice_below_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc lattice below artistic"
  },
  {
    "src": "/Physics/Percolation/perc_lattice_critical_artistic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc lattice critical artistic"
  },
  {
    "src": "/Physics/Percolation/perc_transition.gif",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc transition"
  },
  {
    "src": "/Physics/Percolation/perc_variants_diagnostic.png",
    "topic": "Percolation",
    "topicHref": "/shared/md.html?src=Physics/Percolation/README.md",
    "alt": "perc variants diagnostic"
  }
];
